#!C:\Users\angel\OneDrive\Documentos\.universidad\.2025\mineria\hts\HTD2-MDD\ambienteV\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
